# Generated by Django 5.0.1 on 2024-01-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
