# Generated by Django 5.0.1 on 2024-01-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_weather_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='lang',
            field=models.CharField(default='en', max_length=8),
            preserve_default=False,
        ),
    ]
