# Generated by Django 5.0.1 on 2024-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0004_rename_city_weather_raw_city_weather_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='wind_direction',
            field=models.CharField(choices=[('north', 'North'), ('east', 'East'), ('south', 'South'), ('west', 'West')], max_length=5),
        ),
    ]
